import React from 'react';
import { Project } from '../types';
import { ExternalLink, Github } from 'lucide-react';

const projects: Project[] = [
  {
    id: 'pr1',
    title: 'NeuroLens',
    description: 'An open-source library for visualizing neural network activation patterns in real-time within the browser. Built with WebGL and React.',
    tags: ['WebGL', 'TypeScript', 'Machine Learning'],
    imageUrl: 'https://picsum.photos/600/400?random=1',
    link: '#',
    github: '#'
  },
  {
    id: 'pr2',
    title: 'ZenFocus',
    description: 'A minimalist productivity app that uses ambient soundscapes generated by AI to help users maintain flow state.',
    tags: ['Generative Audio', 'React Native', 'UX Design'],
    imageUrl: 'https://picsum.photos/600/400?random=2',
    github: '#'
  }
];

const Projects: React.FC = () => {
  return (
    <section className="py-20 px-6 max-w-6xl mx-auto">
      <div className="flex items-center gap-4 mb-12">
        <h2 className="text-4xl font-bold text-slate-900">Selected Projects</h2>
        <div className="h-px flex-1 bg-gradient-to-r from-indigo-200 to-transparent"></div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {projects.map((project) => (
          <div 
            key={project.id}
            className="group bg-white/40 rounded-2xl overflow-hidden border border-white/60 hover:shadow-xl hover:shadow-indigo-500/5 transition-all duration-300 hover:-translate-y-1"
          >
            <div className="h-48 overflow-hidden relative">
              <div className="absolute inset-0 bg-indigo-900/10 group-hover:bg-transparent transition-colors z-10"></div>
              <img 
                src={project.imageUrl} 
                alt={project.title} 
                className="w-full h-full object-cover transform group-hover:scale-105 transition-transform duration-700"
              />
            </div>
            
            <div className="p-6 space-y-4 relative z-20 bg-white/50 backdrop-blur-xl">
              <div className="flex justify-between items-start">
                <h3 className="text-xl font-bold text-slate-900">{project.title}</h3>
                <div className="flex gap-2">
                  {project.github && (
                    <a href={project.github} className="text-slate-400 hover:text-indigo-600 transition-colors">
                      <Github size={18} />
                    </a>
                  )}
                  {project.link && (
                    <a href={project.link} className="text-slate-400 hover:text-indigo-600 transition-colors">
                      <ExternalLink size={18} />
                    </a>
                  )}
                </div>
              </div>
              
              <p className="text-slate-600 text-sm leading-relaxed">
                {project.description}
              </p>
              
              <div className="flex flex-wrap gap-2 pt-2">
                {project.tags.map(tag => (
                  <span key={tag} className="px-2 py-1 bg-indigo-50 border border-indigo-100 text-indigo-600 text-xs rounded-md">
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default Projects;