import { Project } from '../types';

export const projects: Project[] = [
  {
    id: 'pr1',
    title: 'NeuroLens',
    description: 'An open-source library for visualizing neural activation patterns in real time within the browser. Built with WebGL and React.',
    tags: ['WebGL', 'TypeScript', 'Machine Learning'],
    imageUrl: 'https://picsum.photos/600/400?random=1',
    link: '#',
    github: '#'
  },
  {
    id: 'pr2',
    title: 'ZenFocus',
    description: 'A minimalist productivity system that uses ambient soundscapes generated by AI to help clinicians sustain focus.',
    tags: ['Generative Audio', 'React Native', 'UX Design'],
    imageUrl: 'https://picsum.photos/600/400?random=2',
    github: '#'
  }
];
